from src.tabs.tab_content import TabContent, ExampleTabContent
from src.tabs.states_tab_content import StatesTabContent
from src.tabs.olympic_tab_content import OlympicTabContent
from src.tabs.coronavirus_tab_content import CoronavirusTabContent
from src.tabs.browsers_tab_content import BrowsersTabContent
from src.tabs.fertility_tab_content import FertilityTabContent